DROP DATABASE IF EXISTS where_does_it_go;
CREATE DATABASE where_does_it_go;
USE where_does_it_go;

CREATE TABLE subCategory(
   categoryID    INTEGER
  ,subcategoryId INTEGER 
  ,subCategory   VARCHAR(33)
);
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (1,1,'Appliances');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (1,2,'Batteries');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (1,3,'Bathroom & Laundry');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (1,4,'Bedroom');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (1,5,'Garage & Outdoor');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (1,6,'Kitchen');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (1,7,'Lights & Bulbs');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (1,8,'Misc Household');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (2,1,'Exterior');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (2,2,'Floors & Ceiling');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (2,3,'Furnaces & Fixtures');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (2,4,'Salvaged Materials');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (2,5,'Soil, Rock, Brick, & Concrete');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (2,6,'Windows & Walls');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (2,7,'Wood Wastes');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (3,1,'Batteries');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (3,2,'CDs, DVDs, or Floppies');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (3,3,'Cell Phones');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (3,4,'Clock Radios');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (3,5,'Computers or Laptops');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (3,6,'Computer Monitors');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (3,7,'Copiers or Fax Machines');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (3,8,'E-readers');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (3,9,'E-waste');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (3,10,'Landline Telephones');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (3,11,'Other Electronic Devices');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (3,12,'Toner or Printer Cartridges');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (3,13,'Printers or Peripherals');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (3,14,'Stereo or Audio Equipment');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (3,15,'Televisions');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (3,16,'VCRs');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (4,1,'Bedding or Linens');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (4,2,'Carpet or Padding');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (4,3,'Clothes or Shoes');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (4,4,'Dryer Sheets');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (4,6,'Fabric or Textiles');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (4,7,'Reusable Shopping Bags');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (5,1,'Cooking Oil');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (5,2,'Fats, Oils, or Grease');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (5,3,'Food Scraps');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (5,4,'Pet Food');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (5,5,'Vitamins');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (6,1,'Aluminum Foil or Trays');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (6,2,'Bags & Pouches');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (6,3,'Bottles & Jugs');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (6,4,'Boxes, Cartons & Liners');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (6,5,'Butter Wrappers');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (6,6,'Compostable Food Service Items');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (6,7,'Corks');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (6,8,'Coffee Filters');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (6,9,'Coffee Pods');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (6,10,'Egg Cartons');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (6,11,'Glass Bottles or Jars');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (6,12,'Hot Cups or Coffee Cups');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (6,13,'Lids');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (6,14,'Metal Cans & Metal Lids');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (6,15,'Paper & Cardboard');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (6,16,'Plastic & Styrofoam Containers');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (6,17,'Straws');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (7,1,'Auto Glass');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (7,2,'Broken Glass');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (7,3,'Drinking Glasses');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (7,4,'Eyeglasses');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (7,5,'Glass Bottles or Jars');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (7,1,'Glass or Ceramic Household Items');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (7,2,'Fluorescent Light Bulbs');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (7,3,'Halogen or Xenon Light Bulbs');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (7,4,'Incandescent Light Bulbs');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (7,5,'LED Light Bulbs');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (7,6,'Mercury Thermometers');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (7,7,'Mirrors');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (7,8,'Mugs, Plates, or Bowls');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (7,9,'Window or Picture Glass');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (8,1,'Aerosol Cans');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (8,2,'Ammunition or Guns');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (8,3,'Asbestos');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (8,4,'Batteries');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (8,5,'Compressed Gas Containers');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (8,6,'Contaminated Dirt or Soil');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (8,7,'Fiberglass');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (8,8,'Fireworks');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (8,9,'Fluorescent Light Bulbs');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (8,10,'Liquids & Household Supplies');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (8,11,'Medicines');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (8,12,'Motor Oil Containers');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (8,13,'Needles or Syringes');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (8,14,'Oil Filters');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (8,15,'Oil Tanks');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (8,16,'Pesticides');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (8,17,'Toner or Printer Cartridges');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (8,18,'Smoke Detectors');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (8,19,'Thermometers or Mercury Items');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (9,1,'Appliances');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (9,2,'Barrels or Drums');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (9,3,'Batteries');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (9,4,'Bicycles or Bike Parts');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (9,5,'Cans');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (9,6,'Compressed Gas Containers');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (9,7,'From the Kitchen');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (9,8,'Hand Tools');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (9,9,'Jewelry or Coins');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (9,10,'Lawn Mowers or Power Equipment');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (9,11,'License Plates');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (9,12,'Metals by Type');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (9,13,'Small Metal Items');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (9,14,'Window Blinds');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (9,15,'Wire Clothes Hangers');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (9,16,'Wire or Cable');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (10,1,'Cardboard');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (10,2,'Containers / Boxes / Cartons');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (10,3,'Food-soiled Paper');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (10,4,'Misc. Paper');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (10,5,'Paper, Printed / Reading');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (11,1,'Bags');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (11,2,'Recycle Numbers 1-7');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (11,3,'Food & Beverage Containers');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (11,4,'Mail Packaging');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (11,5,'Misc. Plastic');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (11,6,'Non-Food Containers');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (11,7,'Straws');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (11,8,'Styrofoam');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (12,1,'Antifreeze');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (12,2,'Auto Glass');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (12,3,'Bicycles or Bike Parts');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (12,4,'Brake or Transmission Fluid');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (12,5,'Car Batteries');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (12,6,'Child Car Seats');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (12,7,'Engines, Motors or Car Parts');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (12,8,'Flares');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (12,9,'Gas Cans');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (12,10,'Gasoline');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (12,11,'Lawn Mowers or Power Equipment');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (12,12,'License Plates');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (12,13,'Motor Oil');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (12,14,'Motor Oil Containers');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (12,15,'Motor Oil Filters');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (12,16,'Other Vehicle Fluids');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (12,17,'Tires');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (12,18,'Vehicles');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (12,19,'Starters, Carburetors, Etc.');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (13,1,'Christmas Trees');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (13,2,'Clean Wood Waste');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (13,3,'Corks');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (13,4,'Fireplace or Briquette Ashes');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (13,5,'Painted or Treated Wood');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (13,6,'Pallets');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (13,7,'Reusable Lumber');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (13,8,'Wood Scraps, Shavings, or Sawdust');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (14,1,'Christmas Trees');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (14,2,'Contaminated Dirt or Soil');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (14,3,'Dirt or Soil');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (14,4,'Grass Clippings or Sod');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (14,5,'House Plants');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (14,6,'Leaves or Non-Woody Yard Waste');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (14,7,'Pet Waste or Litter');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (14,8,'Plant or Tree Salvage');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (14,9,'Plant Pots');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (14,10,'Rocks or Gravel');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (14,11,'Trees or Brush');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (14,12,'Wood Scraps, Shavings, or Sawdust');
INSERT INTO subCategory(categoryID,subcategoryId,subCategory) VALUES (14,13,'Noxious Weeds');

